# Generated by Django 3.0.6 on 2020-05-10 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=datetime.date(2020, 5, 10)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
