# Generated by Django 3.0.6 on 2020-05-12 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200510_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=datetime.date(2020, 5, 12)),
        ),
    ]
