# Generated by Django 3.0.6 on 2020-05-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
