# Generated by Django 3.1.3 on 2020-11-26 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=datetime.date(2020, 11, 26)),
        ),
    ]
