# Generated by Django 3.1.3 on 2020-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201126_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='status',
            field=models.CharField(choices=[('M', 'Married'), ('UM', 'Unmarried')], max_length=30),
        ),
    ]
